services:
  simple_chat_bot:
    container_name: simple_chat_bot_app
    build:
      context: .
      dockerfile: Dockerfile_test
#    image: simple_chat_bot

    ports:
      - 127.0.0.1:8005:8005

    volumes:
      - ~/simple_chat_bot/simple_chat_bot/configs/experiment_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/generate_config.py
      - ~/simple_chat_bot/simple_chat_bot/configs/model_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/model_config.py
      - ~/simple_chat_bot/simple_chat_bot/configs/data_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/data_config.py

  streamlit:
    container_name: streamlit_app
    build:
      context: .
      dockerfile: StreamlitDockerfile
    ports:
      - 443:8501
    volumes:
      - /etc/letsencrypt/live/tschatbotbb.online/fullchain.pem:/etc/simple_chat_bot/fullchain.pem
      - /etc/letsencrypt/live/tschatbotbb.online/privkey.pem:/etc/simple_chat_bot/privkey.pem
    depends_on:
      - simple_chat_bot
