services:
  simple_chat_bot:
    container_name: simple_chat_bot_app
    image: simple_chat_bot

    ports:
      - 8005:8005

    volumes:
      - ~/simple_chat_bot/simple_chat_bot/configs/experiment_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/experiment_config.py
      - ~/simple_chat_bot/simple_chat_bot/configs/model_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/model_config.py
      - ~/simple_chat_bot/simple_chat_bot/configs/data_config.py:/etc/simple_chat_bot/code/simple_chat_bot/configs/data_config.py

  streamlit:
    container_name: streamlit_app
    build:
      context: .
      dockerfile: StreamlitDockerfile
    ports:
      - 8501:8501
    depends_on:
      - simple_chat_bot